### ISSUE TITLE
User info with pictures fail

### ISSUE THREAD

**Issue by lene** [lene/nicotine-plus#46]
User orangeman:
```
Traceback (most recent call last):
  File "/nicotine/pynicotine/gtkgui/userinfo.py", line 470, in ShowUserInfo
    loader.write(pic)
TypeError: Item 0: Must be number, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nicotine/pynicotine/gtkgui/frame.py", line 1382, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/nicotine/pynicotine/pynicotine.py", line 1465, in UserInfoReply
    self.userinfo.ShowInfo(i.username, msg)
  File "/nicotine/pynicotine/gtkgui/userinfo.py", line 125, in ShowInfo
    self.users[user].ShowInfo(msg)
  File "/nicotine/pynicotine/gtkgui/userinfo.py", line 493, in ShowInfo
    self.ShowUserInfo(msg.descr, msg.has_pic, msg.pic, msg.totalupl, msg.queuesize, msg.slotsavail, msg.uploadallowed)
  File "/nicotine/pynicotine/gtkgui/userinfo.py", line 481, in ShowUserInfo
    f.write(pic)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by droserasprout** [comment]
This one reproducing depending on what `ShowUserInfo` get as `pic` argument, `str` or `bytes`.  I've uploaded my own profile picture and it shows in User Info tab. But maybe it's just cached. Investigating.
