### ISSUE TITLE
Copying things to clipboard fails

### ISSUE THREAD

**Issue by lene** [lene/nicotine-plus#52]

**Comment by lene** [comment]
Additionally:
```
Traceback (most recent call last):
  File "/nicotine/pynicotine/gtkgui/search.py", line 1644, in OnCopyURL
    self.frame.SetClipboardURL(user, path)
  File "/nicotine/pynicotine/gtkgui/frame.py", line 2781, in SetClipboardURL
    self.MainWindow.selection_owner_set("PRIMARY", 0)
AttributeError: 'Window' object has no attribute 'selection_owner_set'
```
