### ISSUE TITLE
Errors while downloading

### ISSUE THREAD

**Issue by lene** [lene/nicotine-plus#57]
```
Sat 21:35 Found meta data that couldn't be encoded, possible corrupt file: 'A1 Schleimer K - She's
          Gone.mp3' has a bitrate of 192 kbs, a length of 202 seconds and a VBR of 0
```
and, possibly unrelated,
```
Traceback (most recent call last):
  File "/home/lene/workspace/nicotine+/pynicotine/gtkgui/frame.py", line 1382, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/home/lene/workspace/nicotine+/pynicotine/pynicotine.py", line 1673, in FileDownload
    self.transfers.FileDownload(msg)
  File "/home/lene/workspace/nicotine+/pynicotine/transfers.py", line 1253, in FileDownload
    self.addToShared(newname)
  File "/home/lene/workspace/nicotine+/pynicotine/transfers.py", line 1310, in addToShared
    self.eventprocessor.shares.addToShared(name)
  File "/home/lene/workspace/nicotine+/pynicotine/shares.py", line 1071, in addToShared
    words = self.getIndexWords(dir, file, shareddirs)
  File "/home/lene/workspace/nicotine+/pynicotine/shares.py", line 1034, in getIndexWords
    if os.path.commonprefix([dir, i]) == i:
  File "/usr/lib/python3.8/genericpath.py", line 77, in commonprefix
    m = tuple(map(os.fspath, m))
```

**Comment by lene** [comment]
Downloads succeed though.

**Comment by toofar** [comment]
Stack trace should be fixed by https://github.com/lene/nicotine-plus/pull/55
I saw that "couldn't be encoded" message to but when I restarted and told it to re-scan shares it added them fine. I assumed my testing had borked something, perhaps printing a stack trace along with the message would help identity reproduction steps.

**Comment by lene** [comment]
@toofar, interesting, since merging #59 (based on your PR #55) I no longer get "couldn't be encoded" messages either. I don't see how that PR could have fixed this, but since it does seem to be fixed, I'll keep this issue closed.
